## library() calls go here
#library(conflicted)
library(dotenv)
library(drake)
require(magrittr)
require(AnnotationDbi)
require(org.Mm.eg.db)
require(tidyverse)
require(intrinsicDimension)
require(reticulate)
require(SingleCellExperiment)
require(Seurat)
library(rmarkdown)
library(WGCNA)
library(variancePartition)
library(cowplot)